export {default as Home} from './Home/Home'
export {default as NewDiary} from './Home/NewDiary'
export {default as Authen} from './Authentication/Authen'
export {default as SignIn} from './Authentication/SignIn'
export {default as SignUp} from './Authentication/SignUp'
export {default as ProfileDetail} from './Profile/ProfileDetail'