export {default as Home} from './Home/Home'
export {default as SignIn} from './Authentication/SignIn'
export {default as SignUp} from './Authentication/SignUp'
export {default as ProfileDetail} from './Profile/ProfileDetail'
export {default as DiaryDetail} from './Diary/DiaryDetail'
export {default as NewDiary} from './Diary/NewDiary'